### ISSUE TITLE
Export data/report

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#156] opened 2023-07-10 19:30 UTC
**Description of new feature**

- Allow for exporting the entire enrichment result in a file I can open in Excel. 
- Give me a report of my expression result so that I can save it, reproduce it, etc.

**Motivation for new feature**

- I want the data.  
- I might want to make another chart.
- I want a record of my results.

**Comment by mikekucera** [comment] 2023-07-10 19:32
Duplicate of https://github.com/cytoscape/enrichment-map-webapp/issues/148 ???
The enrichment results file could be opened in Excel or EM-destkop.

**Comment by maxkfranz** [comment] 2023-07-10 19:38
> Duplicate of #148 ???
> The enrichment results file could be opened in Excel or EM-destkop.

Different.  Not Cy but Excel.

**Comment by mikekucera** [comment] 2023-07-10 20:29
User can open TSV in Excel, do they need an actual Excel formatted file? I don't see how this is different.

**Comment by mikekucera** [comment] 2023-07-10 20:33
How exactly is it different? The enrichment results file is TSV which could be opened in Excel. Is it just a separate menu option for clarity? What about the ranks, does the user want that as well?

**Comment by maxkfranz** [comment] 2023-07-10 21:21
So the Cy export is one or more CSVs, then?  Not CYS?  If so, that’s great.  There’s probably overlap for reuse.

The idea here is somewhat more of a report use case, which I didn’t originally encode in the OP.  There may be a lot of similarities with the Cy export use case, but it might not be exactly the same.

**Comment by mikekucera** [comment] 2023-07-10 21:56
My apologies, the contents of issue #148 was not clear about file formats, or what EM-desktop does with the data. I have updated the issue. 

Its the same data in the same format, so lots of overlap. My proposal with #148 is to output the raw enrichment and ranks data in their standard text-based file formats, which is directly importable into EM-desktop. EM-desktop then generates a network like it usually does. This would work right now without any modification to EM-desktop. 

From a UI perspective it would make sense to have separate menu items based on intent. "Export to Excel" for users looking for a report, "Export to Cytoscape" to nudge users towards staying in our ecosystem, or something like that.

**Comment by chrtannus** [comment] 2024-02-08 14:33
The exported files are all tabular and you can use them to recreate the EM results in Cy3. And you can open them in Excel too.
(This should be in the FAQ)

**Closed by chrtannus** 2024-02-08 14:33 UTC
Labels: medium priority
